### ISSUE TITLE
Please add LICENSE/NOTICE to the generated jar

### ISSUE THREAD

**Issue by vlsi** [apiguardian-team/apiguardian#12]
apiguardian-api-1.0.0.jar does not have LICENSE/NOTICE files (e.g. to META-INF/ folder), so it is kind of hard to tell the licensing for the artifact.

It would be nice if you add `Bundle-License` manifest attribute on top of adding LICENSE file: https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.annotation/src/aQute/bnd/annotation/headers/BundleLicense.java

For instance: `Bundle-License: Apache-2.0`

**Comment by marcphilipp** [comment]
We should indeed do this. Thanks for bringing this to our attention! Unfortunately I missed this issue when we released 1.1.0.
