### ISSUE TITLE
When to use API.Status.DEPRECATED?

### ISSUE THREAD

**Issue by Marcono1234** [apiguardian-team/apiguardian#17]
When should `API.Status.DEPRECATED` be used? Normally you would use `@java.lang.Deprecated` which has since Java 9 the elements `since` and `forRemoval` and is likely supported by every IDE.

So what are cases where one would (only) use `API.Status.DEPRECATED`? Is it intended for situations where the public API will be removed, but the annotated element will still be available internally afterwards (though wouldn't `@Deprecated` then be better as well)?

**Comment by rhwood** [comment]
I would use `API.Status.DEPRECATED` when I want to change the API status of a class, while not deprecating it within the Java code.

If I am preparing to make the transition from Java 8 to Java 11, I might also choose to not publish a package in `module-info.java`, and would therefor want to provide warning that all classes in that package will no longer be available. So the classes would be changed from `API.Status.MAINTAINED` to `API.Status.INTERNAL` via `API.Status.DEPRECATED`.

**Comment by Marcono1234** [comment]
Thanks, your example with the module system is good.
Would it make sense to add this to the `API.Status.DEPRECATED` javadoc so for other uses cases where `@Deprecated` is more appropriate, that annotation is used instead (because it has more extensive IDE and tools support)?

**Comment by rhwood** [comment]
@Marcono1234 Probably. I'm not affiliated with this project, but have gone through the exercise I described. I'd submit a PR and see how the project feels about it.

**Comment by marcphilipp** [comment]
@Marcono1234 In the junit5 repo we currently use both `@Deprecated` and `@API(status = API.Status.DEPRECATED)`. The former for IDE support, the latter to adhere to our rule that all visible APIs should have a semantically correct `@API` annotation. We also generate https://junit.org/junit5/docs/current/user-guide/#api-evolution-deprecated-apis from it.

**Comment by Marcono1234** [comment]
I have created the pull request #18 to explain the usage of `Status.DEPRECATED`. I hope it covers both of your use cases well enough and is useful for future users of this library.
