### ISSUE TITLE
Allow @API to be declared at the package level

### ISSUE THREAD

**Issue by TimvdLippe** [apiguardian-team/apiguardian#19]
I am reviewing https://github.com/mockito/mockito/pull/2047 atm, which adds apiguardian statements to various Mockito internal classes that are used by the `mockito-junit-jupiter` extension. This approach is quite ad-hoc, as we would have to add the annotation when we start using it. An alternative approach would be to add the annotation to every single class we have in `org.mockito.internal`, but that seems to be quite invasive as well.

Would it be possible to allow the annotation to be added on package statements (e.g. in a `package-info.java`) for `org.mockito.internal`? That would then indicate that all classes in its (sub-)packages are marked internal.

I am not sure if OSGi tooling would need to be updated to support the new location, but at least it would allow us to more nicely integrate `apiguardian` into Mockito.

CC @rotty3000

**Comment by rotty3000** [comment]
Great idea. We would have to improve bnd to handle this but it's still the right approach.

**Comment by marcphilipp** [comment]
Originally the annotation was introduced to avoid "internal" or "experimental" packages because those cannot be promoted to a different status without breaking backward compatibility. I can see use cases for this, though, so I'd be in favor.

@sbrannen WDYT?

**Comment by sbrannen** [comment]
I think it would be OK to allow `@API` to be declared at the package level, and I'm sure it would be useful in certain scenarios.

The only issue is that doing so will require that tools supporting API Guardian will have to take package-level declarations into account as well, with class-level declarations overriding package-level declarations.

But... perhaps that's an issue for very many people at this point in time.

**Comment by marcphilipp** [comment]
> But... perhaps that's an issue for very many people at this point in time.

You meant to write "_not_ an issue", right?

**Comment by TimvdLippe** [comment]
@sbrannen As I understand it, tools that are currently not processing package statement wouldn't see the annotation either. So I think it would gracefully degrade (e.g. ignore). I guess @rotty3000 could shine a light on that from BND's perspective if that assumption is correct?

**Comment by sbrannen** [comment]
> You meant to write "_not_ an issue", right?

Correct. I'll edit my comment.

**Comment by sbrannen** [comment]
> As I understand it, tools that are currently not processing package statement wouldn't see the annotation either. So I think it would gracefully degrade (e.g. ignore).

Well, I wouldn't call that graceful degradation. If the author assumes the tool honors the package-level declaration and therefore omits superfluous class-level declarations, then the tool would think such classes are not annotated with any form of `@API` declaration, thereby not honoring the author's intent.

**Comment by rotty3000** [comment]
I'll have to double check with a real test case, but from a quick review of the bnd code it seems that package annotation would work with no changes. In other words even an older version of bnd look like they would do the right thing (I will confirm this over the next few days).

**Comment by csierra** [comment]
I also think it would be very useful to have `@API` support at the package level

a +1 from me

**Comment by marcphilipp** [comment]
Is anyone interested in sending a small PR?

**Comment by TimvdLippe** [comment]
I can send a PR. I was mostly waiting on the confirmation of @rotty3000 that the approach will work with BND tooling.

**Comment by rotty3000** [comment]
@TimvdLippe apologies. I've been really busy, but making this work in bnd :) and don't foresee any complications.
