### ISSUE TITLE
Add OSGi metadata

### ISSUE THREAD

**Issue by kriegfrj** [apiguardian-team/apiguardian#22]
From discussion in https://github.com/junit-team/junit5/issues/2547, it was noted that the `@API` annotation of API guardian has `RUNTIME` retention policy - which means that some code might reasonably expect it to be available at runtime. (This is in contrast to a comment made earlier [here](https://github.com/junit-team/junit5/pull/1353#issuecomment-377794249) stating that it was a compile-only dependency.)

Given that runtime retention implies that runtime usage is anticipated, API Guardian should probably at some stage get its own OSGi metadata to make it available at runtime in an OSGi context.

**Comment by marcphilipp** [comment]
@kriegfrj SGTM. Would you be interested in submitting a PR for this?

**Comment by kriegfrj** [comment]
Done!
